### ISSUE TITLE
"No tables found" suddenly

### ISSUE THREAD

**Issue by Panaslonic** [atreadw1492/yahoo_fin#55]
Today code like 

a = si.get_quote_table ( 'AAPL' )

stop worked. When debug, seems, what it suddenly need html5lib. OK, installed. 
Then, when try to run this code, get:

Traceback (most recent call last):

  File "C:/Users/Shake/PycharmProjects/RoboAd/Collector.py", line 1811, in <module>
    a = si.get_quote_table ( 'AAPL' )
  File "C:\Users\Shake\.conda\envs\RobAd\lib\site-packages\yahoo_fin\stock_info.py", line 293, in get_quote_table
    tables = pd.read_html(site)
  File "C:\Users\Shake\.conda\envs\RobAd\lib\site-packages\pandas\io\html.py", line 1100, in read_html
    displayed_only=displayed_only,
  File "C:\Users\Shake\.conda\envs\RobAd\lib\site-packages\pandas\io\html.py", line 915, in _parse
    raise retained
  File "C:\Users\Shake\.conda\envs\RobAd\lib\site-packages\pandas\io\html.py", line 895, in _parse
    tables = p.parse_tables()
  File "C:\Users\Shake\.conda\envs\RobAd\lib\site-packages\pandas\io\html.py", line 213, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "C:\Users\Shake\.conda\envs\RobAd\lib\site-packages\pandas\io\html.py", line 545, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found

**Comment by Vorotori** [comment]
Same here. Seems like it fails at this step:
tables = pd.read_html(site)

Not sure if Yahoo changed the page layout or is it an update of some involved modules?

**Comment by hanseopark** [comment]
same issue
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by atreadw1492** [comment]
I'm looking into it.  It seems to be a change in Yahoo Finance.  In the meantime, you should be able to pull most of the data from si.get_quote_table using si.get_quote_data, instead.

**Comment by Caesurus** [comment]
Ran into the same problem. Looks like yahoo is blocking based on useragent.

You can change the code to:
```tables = pd.read_html(requests.get(site, headers={'User-agent': 'Mozilla/5.0'}).text)```
Just remember to include `import requests` at the top of the file.

I looked at the latest version in `master`, and that is not the same code that i have installed via pip, otherwise i would have created a pull request. 

It would be great to be able to specify the useragent in the `get_options_chain()` call itself. If you'd like me to do a PR to the existing code i'd be happy to when i find time.

**Comment by atreadw1492** [comment]
@Caesurus Thanks a lot!  I merged the request.  I'll push an update to the PyPI version in the next few days.

**Comment by Caesurus** [comment]
Absolutely a pleasure. Thanks for maintaining the module, It's been great using it. So i appreciate it.

**Comment by Caesurus** [comment]
Was just looking through the code and you may need something similar in `get_expiration_dates()` since that looks like it's doing a `.get()` as well.

**Comment by ywluohao** [comment]
@Caesurus @atreadw1492 thank you guys. Can you please also update the function `si.get_quote_table`?

**Comment by atreadw1492** [comment]
@ywluohao Yes, just pushed changes to the other functions affected to the master branch.  I will push the updated version to PyPI after doing additional testing.

**Comment by atreadw1492** [comment]
Updates have now been pushed to PyPI - the latest version is 0.8.9

**Comment by sethbowers97** [comment]
Newer issue encountered using the get_quote_table function. Seems to be due to a yahoo finance html restructure, and it occurs on line 299 in stock_info.py. However, this is only an issue if you seek the entire table, as **the error pertains exclusively with the extraction of the current trade price, which is done using another function referenced in the definition of get_quote_table**. In my case, I was just looking for current volume on the day, for which the following worked wonderfully: ``currentVolume = si.get_quote_table(ticker, dict_result=False).loc[16][1]``.
